### ISSUE TITLE
Meetings, Tracking, and Demos

### ISSUE THREAD

**Issue by AustinGrey** [TransparentGovernanceUofA/TransparentGov#36]
1) Meeting minutes on the team wiki.
2) Evidence that the team works well with the client.
3) The team works well with the TA (asks
questions/advice, reports progress meaningfully,
addresses feedback).
4) The team has made real progress since last sprint..
5) The team has met its own plan for the current
sprint.

**Comment by AustinGrey** [comment]
From the grades page on the wiki, here are the items that Diego wanted worked on:


- [ ] The glossary does not include what a GFC is.
- [ ] US.10 could be rephrased, because I think “guide through a complex search” is not accurate.
- [ ] The components and classes have a few minor inconsistencies regarding the packages and notation.
- [ ] The release plan only considers the next sprint.
- [ ] Issues have to be divided (NLP is too big). Issues have not been assigned.
